//! Each tool's compact JSON in v4 key order; named v5 differences are covered
//! in `tool_schemas.json`. Never reformat the schemas or change their key order.

pub(super) const GET_SCHEDULE: &str = r##"{"type":"function","function":{"name":"get_schedule","description":"Runs for a calendar or boss week: day, time, bosses, status and RSVP count. Use for schedule questions; never offer past runs as next or upcoming. Each run's record is shown under your reply: cite a run by its [id] and never retell its day, time, status, RSVP count or channel. A personal result's 'Context (hidden from members)' line is for you: say its phrases in your own words, never copy the line.","parameters":{"type":"object","properties":{"week":{"type":"string","enum":["this","next","this_boss","next_boss","auto"],"description":"Use 'this' or 'next' for calendar Monday-Sunday weeks. Use 'this_boss' or 'next_boss' only when the member explicitly says boss week. Use 'auto' for a bare weekday or today, tonight, or tomorrow. For 'next run' or 'when is my next' asks, use 'auto' and omit day: it lists the upcoming runs left in this boss week, earliest first. For 'next week', set week to 'next' and omit day."},"scope":{"type":"string","enum":["all","channel"],"description":"Use 'channel' only for explicit 'this channel'/'here'/'our runs'. Bare dates ask the whole group: use 'all' (default). The bot @mention is not a qualifier."},"participant":{"type":"string","description":"Set only for explicit 'for me'/'my runs' or a named member. Bare dates are not personal: omit it. Never copy the bot @mention."},"day":{"type":"string","description":"Optional 'today'/'tonight'/'tomorrow'/weekday. A bare weekday means the next upcoming occurrence; a period-qualified weekday means that weekday inside the requested calendar or boss week. Only set day when the member names a specific day; omit it for whole-week asks."}},"required":["week"]}}}"##;

pub(super) const GET_RUN: &str = r##"{"type":"function","function":{"name":"get_run","description":"One run in full, including who is on it and what each of them answered.","parameters":{"type":"object","properties":{"query":{"type":"string","description":"Which run: its short id from an earlier tool result, or a boss and a day like 'hstar wednesday' or 'kalos tonight'."}},"required":["query"]}}}"##;

pub(super) const LIST_BOSSES: &str = r##"{"type":"function","function":{"name":"list_bosses","description":"The bosses this guild runs, with their difficulties, plus seasonal event bosses that only have a guide. Use it to check a name or to say which guides exist.","parameters":{"type":"object","properties":{},"required":[]}}}"##;

pub(super) const GET_BOSS_STRATEGY: &str = r##"{"type":"function","function":{"name":"get_boss_strategy","description":"Source-backed local strategy notes for one boss. Use this for boss mechanics, phases, dangers, and strategy facts; it returns only checked-in guide content. Also covers seasonal event bosses listed by list_bosses.","parameters":{"type":"object","properties":{"boss":{"type":"string","description":"A boss alias, full name, or canonical token such as 'HFA'."},"difficulty":{"type":"string","description":"Optional difficulty prefix or full name, such as 'h' or 'Hard'."}},"required":["boss"]}}}"##;

pub(super) const GET_PENDING: &str = r##"{"type":"function","function":{"name":"get_pending","description":"Proposal cards that are waiting for somebody to react ✅ or ❌.","parameters":{"type":"object","properties":{},"required":[]}}}"##;

pub(super) const LIST_FIXED: &str = r##"{"type":"function","function":{"name":"list_fixed","description":"Recurring weekly timings: boss, weekday, time and party. Use it to see weeklies before changing one, instead of guessing from the schedule.","parameters":{"type":"object","properties":{},"required":[]}}}"##;

pub(super) const PROPOSE_MOVE: &str = r##"{"type":"function","function":{"name":"propose_move","description":"Post a card proposing that ONE dated run moves to a new day and time -- that night only, leaving the rest of the schedule alone. If they mean the recurring weekly itself (\"change the weekly to 23:30\", \"we do it on Wednesdays now\"), use propose_change_fixed instead. This does NOT move the run: somebody has to react ✅ on the card first.","parameters":{"type":"object","properties":{"run_query":{"type":"string","description":"Which run: its short id from an earlier tool result, or a boss and a day like 'hstar wednesday' or 'kalos tonight'."},"to_when":{"type":"string","description":"The new day and time, e.g. 'wed 21:30' or 'tomorrow 9:45pm'."}},"required":["run_query","to_when"]}}}"##;

pub(super) const PROPOSE_ADD: &str = r##"{"type":"function","function":{"name":"propose_add","description":"Propose a NEW run. Default: ONE-TIME. Set `weekly` true for explicit recurrence, including 'set up a recurring run every Friday'; recurring does not imply an existing weekly. Never use this to change a weekly that already exists; use propose_change_fixed. Needs ✅.","parameters":{"type":"object","properties":{"boss":{"type":"string","description":"One complete difficulty-qualified boss. Use EITHER a canonical token such as 'XBM', 'HBellona', or 'XKalos', OR words with the difficulty first, such as 'Extreme Black Mage' or 'Hard Bellona'. Do not combine forms or add a second difficulty: 'XBM Hard' is invalid; 'extreme bm' means 'XBM'. A bare boss name without a difficulty is refused -- ask which one they mean."},"when":{"type":"string","description":"The day and time, e.g. 'today 21:30' or 'sat 9pm'."},"participants":{"type":"string","description":"Optional comma-separated names, 'me', or Discord mentions (`<@123>`). Mentions are exact: pass them as written; never ask for names/tags. Omit for just the asker. For 'for me' or 'for us', include the asker too. Turns are labelled with who said it."},"weekly":{"type":"boolean","description":"Optional, default false = one run that day only. True ONLY for explicit repeats ('weekly'/'every week'/'every Tuesday'/'recurring'/'fixed', even as a second sentence). Existing run asked to repeat uses this too (scheduler folds it into a weekly, no duplicate). Unclear wording: leave it out."},"extra":{"type":"boolean","description":"Optional, default false. True ONLY after this tool refused the run as a repeat of one already scheduled and they clearly want a second, separate run."}},"required":["boss","when"]}}}"##;

pub(super) const PROPOSE_CANCEL: &str = r##"{"type":"function","function":{"name":"propose_cancel","description":"Post a card proposing that ONE dated run is cancelled -- a single night off. For the recurring weekly baseline (\"remove the fixed run\", \"stop doing this every week\") use propose_remove_fixed instead. This does NOT cancel anything: somebody has to react ✅ on the card first.","parameters":{"type":"object","properties":{"run_query":{"type":"string","description":"Which run: its short id from an earlier tool result, or a boss and a day like 'hstar wednesday' or 'kalos tonight'."}},"required":["run_query"]}}}"##;

pub(super) const PROPOSE_REMOVE_FIXED: &str = r##"{"type":"function","function":{"name":"propose_remove_fixed","description":"Post a card proposing that a RECURRING weekly timing is removed, so the boss stops being scheduled every week. This is not the same as cancelling one night -- for a single dated run use propose_cancel. If it is unclear which they mean, ask: \"just this week's run, or the weekly one?\" This does NOT remove anything: somebody has to react ✅ on the card first.","parameters":{"type":"object","properties":{"query":{"type":"string","description":"Which weekly timing: its short id, or a boss and (if there are several) a day, like 'weekly hbellona' or 'bellona tuesday'."}},"required":["query"]}}}"##;

pub(super) const PROPOSE_CHANGE_FIXED: &str = r##"{"type":"function","function":{"name":"propose_change_fixed","description":"Propose changes to an identified EXISTING weekly: day, time, party, or both. Not for one dated run (use propose_move) or 'set up/create a recurring run' (use propose_add with `weekly` true). When changing one, never reach for propose_add: that creates a duplicate. Needs ✅.","parameters":{"type":"object","properties":{"query":{"type":"string","description":"Which weekly timing: its short id from an earlier tool result, or the boss and the day it runs on NOW, like 'hlimbo monday'. A channel can have several weekly timings -- even two for the same boss on different nights -- so give the boss AND its current day, and the time too if that is still not enough. If you cannot tell which one they mean, ask them; never pick one yourself."},"day":{"type":"string","description":"Optional. The new day of the week it should happen on, e.g. 'wednesday'. Leave it out when only the time changes."},"time":{"type":"string","description":"Optional. The new start time, e.g. '23:30' or '9:30pm'. Leave it out when only the day changes."},"participants":{"type":"string","description":"Optional WHOLE party, not only the people joining or leaving: names, 'me', or Discord mentions (`<@123>`). Mentions are exact: pass them as written; never ask for names/tags. Include the person asking for 'add me to the weekly'; turns are labelled with who said it. Omit to keep the party."}},"required":["query"]}}}"##;

pub(super) const PROPOSE_RSVP: &str = r##"{"type":"function","function":{"name":"propose_rsvp","description":"Post a card recording the answer of the person you are talking to for one run. Only ever for them -- you cannot answer on anybody else's behalf.","parameters":{"type":"object","properties":{"run_query":{"type":"string","description":"Which run: its short id from an earlier tool result, or a boss and a day like 'hstar wednesday' or 'kalos tonight'."},"answer":{"type":"string","enum":["yes","no"],"description":"Whether the person speaking to you can make that run."}},"required":["run_query","answer"]}}}"##;

/// v5 only (dynamic tool loading): the escape hatch offered every round.
pub(super) const REQUEST_TOOLS: &str = r##"{"type":"function","function":{"name":"request_tools","description":"Get more tools when yours cannot do what they asked. Once per message.","parameters":{"type":"object","properties":{"bundle":{"type":"string","enum":["strategy","run_changes","weekly_changes"],"description":"strategy: boss mechanics. run_changes: move, add, cancel or RSVP one run. weekly_changes: change or remove a weekly, or make a run weekly."}},"required":["bundle"]}}}"##;
