"""Build the portal's deployable stylesheet from its ordered partials."""

from __future__ import annotations

import argparse
import re
from functools import lru_cache
from pathlib import Path

STATIC_DIR = Path(__file__).resolve().parent / "api/static"
ENTRYPOINT = STATIC_DIR / "portal.scss"
OUTPUT = ENTRYPOINT.with_suffix(".css")
USE = re.compile(r'^@use "(?P<module>[^"]+)";\s*$', re.MULTILINE)
COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
GENERATED_HEADER = "/* Generated by python -m bot.portal_styles; do not edit directly. */\n\n"


class Arguments(argparse.Namespace):
    output: Path = OUTPUT


def partials(entrypoint: Path = ENTRYPOINT) -> list[Path]:
    """Resolve the entrypoint's ordered ``@use`` declarations."""
    source = entrypoint.read_text(encoding="utf-8")
    modules = [match.group("module") for match in USE.finditer(source)]
    remainder = COMMENT.sub("", USE.sub("", source)).strip()
    if remainder or not modules:
        raise ValueError(f"{entrypoint} must contain only comments and @use declarations")

    resolved: list[Path] = []
    for module in modules:
        path = Path(module)
        resolved.append(entrypoint.parent / path.parent / f"_{path.name}.scss")
    return resolved


@lru_cache(maxsize=1)
def build_stylesheet(entrypoint: Path = ENTRYPOINT) -> str:
    """Join the CSS-compatible partials in entrypoint order."""
    return GENERATED_HEADER + "".join(
        path.read_text(encoding="utf-8") for path in partials(entrypoint)
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    _ = parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT,
        help=f"output path (default: {OUTPUT})",
    )
    args = parser.parse_args(namespace=Arguments())
    output = args.output
    _ = output.write_text(build_stylesheet(), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
